listen_addresses = '*'
ssl = on
ssl_cert_file = '/tls/server.crt'
ssl_key_file = '/tls/server.key'
ssl_ca_file = '/tls/ca.crt'
password_encryption = 'scram-sha-256'
wal_level = replica
archive_mode = on
archive_timeout = 300
archive_command = '/usr/bin/python3 /opt/nambadrive/wal.py %p %f /independent-wal'
logging_collector = off
log_statement = 'none'
log_min_error_statement = panic
log_connections = off
log_disconnections = off
