import uuid

PERMISSIONS = frozenset(
    "VIEW PREVIEW CREATE EDIT RENAME MOVE COPY DELETE DOWNLOAD PRINT "
    "CLIPBOARD_COPY UPLOAD_NEW_VERSION CREATE_FOLDER SHARE CHANGE_ACL VIEW_VERSION_HISTORY "
    "RESTORE_VERSION EXPORT_PDF RESTORE PURGE EXTERNAL_SHARE "
    "REQUEST_ACCESS_DISCOVERY CREATE_SPACE MANAGE_RETENTION MANAGE_LEGAL_HOLD "
    "MANAGE_QUOTAS RECEIVE_ADMIN_ALERTS".split()
)
ROLES = (
    "SYSTEM_ADMIN",
    "STORAGE_ADMIN",
    "SECURITY_ADMIN",
    "SPACE_OWNER",
    "FOLDER_OWNER",
    "DOCUMENT_OWNER",
    "EDITOR",
    "REVIEWER",
    "READER",
    "GUEST",
)
DEFAULTS = {
    "EDITOR": {"VIEW", "PREVIEW", "EDIT", "UPLOAD_NEW_VERSION"},
    "REVIEWER": {"VIEW", "PREVIEW"},
    "READER": {"VIEW", "PREVIEW"},
}
SENSITIVE = frozenset({"DOWNLOAD", "PRINT", "CLIPBOARD_COPY", "EXPORT_PDF"})
BREAK_GLASS_PERMISSIONS = PERMISSIONS - {
    "PURGE",
    "SHARE",
    "EXTERNAL_SHARE",
    "CHANGE_ACL",
    "CREATE_SPACE",
    "MANAGE_RETENTION",
    "MANAGE_LEGAL_HOLD",
    "MANAGE_QUOTAS",
    "RECEIVE_ADMIN_ALERTS",
}


def role_id(name: str) -> uuid.UUID:
    return uuid.uuid5(uuid.NAMESPACE_URL, "https://nambadrive.local/roles/" + name)
