Foreground true
TCPSocket 3310
TCPAddr 0.0.0.0
DatabaseDirectory /var/lib/clamav
User clamav
ScanArchive true
ScanPDF true
ScanOLE2 true
ScanXMLDOCS true
AlertEncrypted true
AlertExceedsMax true
StreamMaxLength 500M
MaxFileSize 500M
MaxScanSize 1000M
MaxRecursion 16
MaxFiles 10000
MaxScanTime 120000
ReadTimeout 120
CommandReadTimeout 30
SelfCheck 600
